---
# This is the configuration file for the Nanopore cDNA differential expression tutorial.
# The configuration must be specified in YAML format

# indentation is required as in this template - a single indent is 4 spaces


pipeline: "Nanopore cDNA gene expression profiling"

reference_genome: "ftp://ftp.ensembl.org/pub/release-94/fasta/homo_sapiens/dna/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz"

genome_annotation: "ftp://ftp.ensembl.org/pub/release-94/gtf/homo_sapiens/Homo_sapiens.GRCh38.94.gtf.gz"

project: "ONT_RNASeq" #Hier könnt ihr dem Projekt einen Namen geben.

Samples:
    - "DMSO":   # this is a group
        A1: "fastq/DMSO_replicate1.fastq.gz"	# these are the files
        A2: "fastq/DMSO_replicate2.fastq.gz"
        A3: "fastq/DMSO_replicate3.fastq.gz"

    - "BaP":
        B1: "fastq/BaP_replicate1.fastq.gz"
        B2: "fastq/BaP_replicate2.fastq.gz"
        B3: "fastq/BaP_replicate3.fastq.gz"

    - "PCB":
        C1: "fastq/PCB_replicate1.fastq.gz"
        C2: "fastq/PCB_replicate2.fastq.gz"
        C3: "fastq/PCB_replicate3.fastq.gz"

referenceGroup: "DMSO"   # Muss identisch zu einer der Gruppenbeschreibungen sein. Denominator / Nenner

treatedGroup: "BaP" # Muss genau so wie die Samples beschrieben sein! Numerator / Zähler

readCountMinThreshold: 10   # what is the minimum number of transcripts for a gene feature to be considered
lfcThreshold : 1.5          # minimum required log2 fold change for differential expression analysis
adjPValueThreshold: 0.05    # adjusted p-value threshold for differential expression analysis
topVarianceGenes: 50        # number of genes with the highest variance depicted in the variance heatmap
cutoff_geneCount: 10        # min number of counts per gene over all samples
minGSSize: 5                # min number of Genes for a Gene Set Enrichment Analysis
maxGSSize: 100              # max number of Genes for a Gene Set Enrichment Analysis
pCutoff_Volcano: 10e-20     # Threshold adjusted p-value for volcano plots
genes_volcano: 10           # number of labelled genes in volcano plot
